server:
  port: 8080

spring:
  application:
    name: TERRA_CLUSTER_OPITA
  banner:
    location: BANNER_LOCATION.txt
    # No mostrar banner
    # main:
    # banner-mode: off
  ## SQLite BBDD Connection
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/app/data/app.db
  sql:
    init:
      mode: always
  jpa:
    properties:
        # Mostrar Mensajes SQL en Consola
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect

logging:
  pattern:
    dateformat: hh:mm
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
